### PR TITLE
[WIP] Better errors

### PR DESCRIPTION
**Pull request by alexji**
Added several things that improve error bars in synthesis, and a few convenience functions.

* [IMPORTANT] allow negative flux values in read_fits_multispec (keeps them, and turns ivar to a tiny number; it might actually be right to leave the ivar untouched though)
* some hacks to spectrum file reading given some nonstandard file types
* Code to calculate stellar parameter errors
* Statistical errors and upper limits for syntheses
* Export basic synthesis figure
* SNR calculation utility function
* A "better" radial velocity error (from Kelson et al 2003: assuming pixel errors are right, the cross-correlation is proportional to chi^2. Not strictly right, but very close.)

* introduced a bug with plotting stellar parameter slope lines. Once this is fixed then PR should be complete.

A lot of this stuff is implemented and accessible in scripts, but not (yet) included in the GUI.

### CODE REVIEW

**Comment by alexji** [comment]
I have fixed many bugs in the GUI, added automatic stellar parameter optimization, and added stellar parameter error calculation.

I have also introduced a unified (but very slow) interface among Profile and Synthesis spectral models for calculating errors.
* Statistical errors can be found with `spectral_model.find_error()`. This adds the key `1_sigma_abundance_error` (and `1_sigma_eqw_error` for profiles) to `spectral_model.metadata`
* Systematic errors (propagating stellar parameter errors) can be found with `spectral_model.propagate_stellar_parameter_error()`. This adds the keys `systematic_abundance_error` and `systematic_stellar_parameter_abundance_error` to `spectral_model.metadata`

**Comment by alexji** [comment]
Note: I just realized this PR is to v0.2. However, master is now past v0.21.

This can be merged into v0.2 and then directly into master.

**Comment by alexji** [comment]
@andycasey I think I have only done good things relative to versions 0.2, 0.21, and master. So I think this should just be merged into master right now.

As a note:
* The best revert point in case of catastrophic failure is v0.2.
* The best revert point in terms of not-completely-tested things is v0.21. But this has already been merged into master and seems to be working well.

**Comment by andycasey** [comment]
I trust you and am happy for this to go straight to master. If you want me to take a detailed look then it will be at least a week or two before I can. 

RE negative fluxes and ivars: ivars can go to tiny or even to zero if fluxes are negative. Better to correct them to tiny/zero (as you have done) than to leave as is.

Should we slate a period of time in our calendars to write The Big Update?

**Comment by alexji** [comment]
OK: I am going to close this pull request WITHOUT merging (because right now it diffs from v0.2).
Then I will make a new pull request to master and merge it in.

Yes, let's find a time for The Big Update!

**Pull request closed without merging**
