### PR TITLE
Alex mods

### PR DESCRIPTION
**Pull request by alexji**
Alex's recent modifications
* included Andy's old optimize SP code
* Base for GUI refactor
* GUI squish
* Upper limit hack
* refactor some linelist importing
* include alpha/Fe
* export EQW lines and abunds
* speed up line loading (using binary search on hashes)
* some random bugfixes

### CODE REVIEW

**Comment by maddiecain** [comment]
Does this branch have the new changes in SMH?

**Comment by alexji** [comment]
Yes this is the currently stable version (including the fix to #225). I'm working on a lot of under the hood changes which should be ready at the start of next week. However one of the things we did is overhaul the internal save structure; I have a conversion script to update when that's ready. It should greatly speed up loading and file sizes.

Maybe this is relevant for Abdu too because the new format should be simpler for the new database.

**Comment by abdu13** [comment]
I put the new smh extraction tool on hold for now until you finish all the internal work.

**Comment by maddiecain** [comment]
Ok thanks! So it does contain the corrections for cool metal-poor stars?

**Comment by alexji** [comment]
Unfortunately it does not contain the corrections yet. I need to add a flag
to SMHR still (will be later today), and also you need to make sure to
install my MOOG (https://github.com/alexji/moog17scat).

You'll be able to tell if something is different because it will take a lot
longer to calculate abundances :)

**Pull request merged**
